In [1]:
import pandas as pd

In [4]:
movo_27 = pd.read_csv("./Volana/Fideicomiso/JERS/data/2024-05-27/MOVO_2024-05-27.txt", sep = '|', 
            names= [
    "Contrato", "Anexo", "Número de documento", "Fecha Depósito", "Fecha Aplicación",
    "Monto de Principal", "Monto de interés", "Monto de IVA", "Tipo de Movimiento", "Cuenta", "paymentId"
])

movo_26 = pd.read_csv("./Volana/Fideicomiso/JERS/data/2024-05-26/MOVO_2024-05-26.txt", sep = '|', 
            names= [
    "Contrato", "Anexo", "Número de documento", "Fecha Depósito", "Fecha Aplicación",
    "Monto de Principal", "Monto de interés", "Monto de IVA", "Tipo de Movimiento", "Cuenta", "paymentId"
])

movo_23 = pd.read_csv("./Volana/Fideicomiso/JERS/data/2024-05-23/MOVO_2024-05-23.txt", sep = '|', 
            names= [
    "Contrato", "Anexo", "Número de documento", "Fecha Depósito", "Fecha Aplicación",
    "Monto de Principal", "Monto de interés", "Monto de IVA", "Tipo de Movimiento", "Cuenta", "paymentId"
])

movo_21 = pd.read_csv("./Volana/Fideicomiso/JERS/data/2024-05-21/MOVO_2024-05-21.txt", sep = '|', 
            names= [
    "Contrato", "Anexo", "Número de documento", "Fecha Depósito", "Fecha Aplicación",
    "Monto de Principal", "Monto de interés", "Monto de IVA", "Tipo de Movimiento", "Cuenta", "paymentId"
])

movo_20 = pd.read_csv("./Volana/Fideicomiso/JERS/data/2024-05-20/MOVO_2024-05-20.txt", sep = '|', 
            names= [
    "Contrato", "Anexo", "Número de documento", "Fecha Depósito", "Fecha Aplicación",
    "Monto de Principal", "Monto de interés", "Monto de IVA", "Tipo de Movimiento", "Cuenta", "paymentId"
])

In [5]:
movo_27.query("Contrato == 185930").sort_values(by = 'Fecha Aplicación', ascending=False)

,Contrato,Anexo,Número de documento,Fecha Depósito,Fecha Aplicación,Monto de Principal,Monto de interés,Monto de IVA,Tipo de Movimiento,Cuenta,paymentId
44411,185930,N,114612,2024-05-24,2024-05-25,-227.62,-839.12,-134.26,PAG,BANCOMER,277643
44277,185930,N,114612,2024-05-18,2024-05-20,-1928.37,-860.90,-137.74,PAG,BANCOMER,276749
44217,185930,N,114612,2024-05-17,2024-05-18,-2093.25,-948.92,-151.83,PAG,BANCOMER,276572
44246,185930,N,114612,2024-05-17,2024-05-17,-1201.00,0.00,0.00,PAG,BANCOMER,276514
43956,185930,N,114612,2024-05-10,2024-05-13,-29.87,-1009.59,-161.54,PAG,BANCOMER,275064
44016,185930,N,114612,2024-05-11,2024-05-13,-5068.42,-907.40,-145.18,PAG,BANCOMER,275158
43662,185930,N,114612,2024-05-03,2024-05-04,-2553.56,-1160.72,-185.72,PAG,BANCOMER,274021
43667,185930,N,114612,2024-05-03,2024-05-04,-2423.37,-860.89,-137.74,PAG,BANCOMER,274024
43461,185930,N,114612,2024-04-29,2024-04-29,0.00,-860.89,-137.74,PAG,BONIFICACION,272664

In [6]:
movo_26.query("Contrato == 185930").sort_values(by = 'Fecha Aplicación', ascending=False)

,Contrato,Anexo,Número de documento,Fecha Depósito,Fecha Aplicación,Monto de Principal,Monto de interés,Monto de IVA,Tipo de Movimiento,Cuenta,paymentId
44210,185930,N,114670,2024-05-17,2024-05-18,-2093.25,-948.92,-151.83,PAG,BANCOMER,276572
44244,185930,N,114670,2024-05-17,2024-05-17,-1201.00,0.00,0.00,PAG,BANCOMER,276514
43940,185930,N,114670,2024-05-10,2024-05-13,-29.87,-1009.59,-161.54,PAG,BANCOMER,275064
44016,185930,N,114670,2024-05-11,2024-05-13,-5068.42,-907.40,-145.18,PAG,BANCOMER,275158
43666,185930,N,114670,2024-05-03,2024-05-04,-2423.37,-860.89,-137.74,PAG,BANCOMER,274024
43671,185930,N,114670,2024-05-03,2024-05-04,-2553.56,-1160.72,-185.72,PAG,BANCOMER,274021
43449,185930,N,114670,2024-04-29,2024-04-29,0.00,-860.89,-137.74,PAG,BONIFICACION,272664

In [7]:
movo_23.query("Contrato == 185930").sort_values(by = 'Fecha Aplicación', ascending=False)

,Contrato,Anexo,Número de documento,Fecha Depósito,Fecha Aplicación,Monto de Principal,Monto de interés,Monto de IVA,Tipo de Movimiento,Cuenta,paymentId
44211,185930,N,114670,2024-05-17,2024-05-18,-2093.25,-948.92,-151.83,PAG,BANCOMER,276572
44228,185930,N,114670,2024-05-17,2024-05-17,-1201.00,0.00,0.00,PAG,BANCOMER,276514
43962,185930,N,114670,2024-05-10,2024-05-13,-29.87,-1009.59,-161.54,PAG,BANCOMER,275064
44030,185930,N,114670,2024-05-11,2024-05-13,-5068.42,-907.40,-145.18,PAG,BANCOMER,275158
43679,185930,N,114670,2024-05-03,2024-05-04,-2423.37,-860.89,-137.74,PAG,BANCOMER,274024
43684,185930,N,114670,2024-05-03,2024-05-04,-2553.56,-1160.72,-185.72,PAG,BANCOMER,274021
43471,185930,N,114670,2024-04-29,2024-04-29,0.00,-860.89,-137.74,PAG,BONIFICACION,272664